### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by stuartcrobinson** [marioperezhurtado/DatsCap#1]
hi, i'm trying to learn supabase, react, and tanstack's react-table so i'd like to try out your project

i got this error when running your startup sql code in supabase's client editor:

`Failed to validate sql query: syntax error at or near "on"`

caused by this bit:

```
create table reactions (
  user_id uuid references profiles (id) primary key on delete cascade,
  cap_id uuid references caps (id) primary key on delete cascade,
  reaction boolean
  favorite boolean
);
```

suggestions?

**Comment by stuartcrobinson** [comment]
i removed `primary key` and added a comma after `reaction boolean` for now

**Comment by marioperezhurtado** [comment]
Thanks for the info! Can you reply with your new sql query so I can change it?

**Comment by marioperezhurtado** [comment]
The reactions table has a composed primary key formed by "user_id" and "cap_id". This sql query was trying to create two different primary keys, and that is wrong.

I am new to postgresql, so I just copied the queries generated with [supabase schema](https://github.com/zernonia/supabase-schema). 

Check the new sql query in [readme](https://github.com/marioperezhurtado/DatsCap#-supabase-setup).

**Comment by stuartcrobinson** [comment]
hi mario!  okay that's helpful about the composed primary key.  i'm new to this stuff too so i'm not totally sure this is missing something but this seems to work for me:

```
create table reactions (
  user_id uuid references profiles (id) on delete cascade,
  cap_id uuid references caps (id) on delete cascade,
  reaction boolean,
  favorite boolean,
  PRIMARY KEY (user_id, cap_id)
);
```
